# Generated by Django 5.0.6 on 2024-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorodageroi',
            name='infa',
        ),
        migrations.RemoveField(
            model_name='gorodageroi',
            name='name',
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='bigGeroi',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='latGeroi',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='longGeroi',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='nameGeroi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='rankGeroi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='smallGeroi',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
