# Generated by Django 5.0.6 on 2024-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_gorodageroi_infa_remove_gorodageroi_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorodageroi',
            name='rankGeroi',
            field=models.CharField(max_length=30),
        ),
    ]
