# Generated by Django 5.0.6 on 2024-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_alter_gorodageroi_rankgeroi'),
    ]

    operations = [
        migrations.CreateModel(
            name='gorodaDoblesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankDoblesti', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('smallDoblesti', models.CharField(blank=True, max_length=10000)),
                ('bigDoblesti', models.CharField(blank=True, max_length=10000)),
                ('longDoblesti', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latDoblesti', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='gorodaSlavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankSlavi', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('smallSlavi', models.CharField(blank=True, max_length=10000)),
                ('bigSlavi', models.CharField(blank=True, max_length=10000)),
                ('longSlavi', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latSlavi', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='gorodageroi',
            old_name='nameGeroi',
            new_name='name',
        ),
    ]
