# Generated by Django 5.0.6 on 2024-06-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_gorodadoblesti_gorodaslavi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gorodadoblesti',
            old_name='name',
            new_name='nameDoblesti',
        ),
        migrations.RenameField(
            model_name='gorodageroi',
            old_name='name',
            new_name='nameGeroi',
        ),
        migrations.RenameField(
            model_name='gorodaslavi',
            old_name='name',
            new_name='nameSlavi',
        ),
    ]
