# Generated by Django 5.0.6 on 2024-06-10 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_rename_name_gorodadoblesti_namedoblesti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorodadoblesti',
            name='pictDoblesti',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorodageroi',
            name='pictGeroi',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorodaslavi',
            name='pictSlavi',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
